name: SODREWSKI
favicon: null
layout_spectrum: 0.24154
typography_spectrum: 0.86003
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2837'
    - '#020202'
    - '#f6d2d4'
    - '#9a9369'
    - '#8d604d'
  brandStrength: 0.546595
  lightness: 0.6773451813496649
  saturation: 0.4206837250385433
  rhythmicContrast: 0.8584418408572674
purpose: []
